[build-system]
requires = [
  "setuptools==68.2.2",
  "Cython==3.0.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "mini_yt"
version = "0.0"
requires-python = "==3.12.0"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false