[build-system]
requires = [
  "setuptools>=61.2",
  "Cython>=3.0, <3.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "mini_yt"
version = "0.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.19.3",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false